# Generated by Django 2.2.2 on 2019-06-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='display',
            new_name='display_type',
        ),
    ]
